#!C:\Users\20202077\OneDrive - TU Eindhoven\TUE\2526\6EMA04\MRM-Assignment\pymrm_env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
